server:
  port: 8001

spring:
  application:
    name: cloud-payment-service  #服务名称
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver  #org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud_order?characterEncoding=utf-8&useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:mappers/*.xml
  type-aliases-package: com.tang.springcloud.entity    # 所有Entity别名类所在包
  configuration:
    map-underscore-to-camel-case: true  #是否开启驼峰命名自动映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl